name: PI for Workpath LogDaemon

on:
  pull_request:
    branches: [ "master" ]
    types: [ opened, synchronize, reopened ]
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  Build_Tests:

    runs-on: [ self-hosted ]
    env:
      UNIT_FILENAME: "testDebugUnit_PR_${{ github.event.number }}.tar.gz"
      WORFING_FOLDER: ${{ vars.PI_WORKING_FOLDER }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /*
          sparse-checkout-cone-mode: false
          path: ${{ vars.PI_WORKING_FOLDER }}

      - name: "Set up OpenJDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: "[Preparation] Grant execute permission for gradlew"
        if: runner.os == 'Linux'
        run: chmod +x gradlew

      - name: "[Preparation] Check if ANDROID_HOME is set"
        if: runner.os == 'Windows'
        run: |
          if (Test-Path env:ANDROID_HOME) {
            Write-Output "ANDROID_HOME is set to: $env:ANDROID_HOME"
          } else {
            Write-Output "ANDROID_HOME is not set"
          }

        ################### Build  ###################
      - name: "[Build] Clean before building"
        working-directory: ./${{ env.WORFING_FOLDER }}
        run: ./gradlew clean

      - name: "[Build] Build with Gradle"
        working-directory: ./${{ env.WORFING_FOLDER }}
        run: ./gradlew build -x test

        ################### Unit Tests  ###################
      - name: "[UnitTest] Run Android Unit Tests (v1.0.1)"
        working-directory: ./${{ env.WORFING_FOLDER }}
        run: ./gradlew :app:testDebugUnitTest

      - name: "[UnitTest] Compress Unit test results"
        working-directory: ./${{ env.WORFING_FOLDER }}/build/modules/app/reports/tests
        if: ${{ failure() || success() }}
        run: tar -czf ./${{ env.UNIT_FILENAME }} ./testDebugUnitTest
